### ISSUE TITLE
draft fails to compile

### ISSUE THREAD

**Issue by mouse07410** [seanturner/draft-turner-lamps-nist-pqc-kem-certificates#19]
```
$ cd draft-turner-lamps-nist-pqc-kem-certificates/
$ make
git clone -q --depth 10  \
    -b main https://github.com/martinthomson/i-d-template lib
lib/main.mk:21: Forcing rebuild of .targets.mk
cat draft-turner-lamps-nist-pqc-kem-certificates.md  | kramdown-rfc2629 --v3 | lib/add-note.py | xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/ur20980/.cache/xml2rfc --v2v3 /dev/stdin -o /dev/stdout >draft-turner-lamps-nist-pqc-kem-certificates.xml
*** attributes left {"venue"=>{"group"=>"Limited Additional Mechanisms for PKIX and SMIME (lamps)", "type"=>"Working Group", "mail"=>"spasm@ietf.org", "arch"=>"https://mailarchive.ietf.org/arch/browse/spasm/", "github"=>"seanturner/draft-turner-lamps-nist-pqc-kem-certificates"}}!
/Users/ur20980/.cache/xml2rfc/reference.RFC.5280.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.5280.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.5280.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.5280.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.5280.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.5280.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.2119.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.2119.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.2119.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.2119.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.8174.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.8174.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.8174.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.8174.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.8174.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.8174.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.5912.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.5912.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.5912.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.5912.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.5912.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.5912.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.5958.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.5958.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.5958.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.5958.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.5958.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.5958.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.7468.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.7468.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.7468.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.7468.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.7468.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.7468.xml
xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/ur20980/.cache/xml2rfc draft-turner-lamps-nist-pqc-kem-certificates.xml -o draft-turner-lamps-nist-pqc-kem-certificates.txt --text --no-pagination
/Users/ur20980/src/draft-turner-lamps-nist-pqc-kem-certificates/draft-turner-lamps-nist-pqc-kem-certificates.xml(166): Error: Cannot build a href for <xref target="RFC5280"> with a section= attribute without also having a relative= attribute.
Not creating output file due to errors (see above)
Unable to complete processing draft-turner-lamps-nist-pqc-kem-certificates.xml
make: *** [lib/main.mk:122: draft-turner-lamps-nist-pqc-kem-certificates.txt] Error 1
rm draft-turner-lamps-nist-pqc-kem-certificates.xml
$ 
```

**Comment by mouse07410** [comment]
```
$ make fix-lint
for f in draft-turner-lamps-nist-pqc-kem-certificates.md; do \
	  [  -z "$(tail -c 1 "$f")" ] || echo >>"$f"; \
	done
sed -i~ -e 's/ *$//' draft-turner-lamps-nist-pqc-kem-certificates.md
if ! git rev-parse --abbrev-ref refs/remotes/origin/HEAD >/dev/null 2>&1; then \
	  echo "ref: refs/remotes/origin/$(git rev-parse --abbrev-ref HEAD)" > $(git rev-parse --git-dir)/refs/remotes/origin/HEAD; \
	fi
$ time make
cat draft-turner-lamps-nist-pqc-kem-certificates.md  | kramdown-rfc2629 --v3 | lib/add-note.py | xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/Users/ur20980/.cache/xml2rfc --v2v3 /dev/stdin -o /dev/stdout >draft-turner-lamps-nist-pqc-kem-certificates.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.5280.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.5280.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.5280.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.5280.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.5280.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.5280.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.2119.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.2119.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.2119.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.2119.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.8174.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.8174.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.8174.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.8174.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.8174.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.8174.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.5912.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.5912.xml
*** Can't get with persistent HTTP: execution expired
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.5912.xml
*** No such file or directory @ rb_sysopen - /Users/ur20980/.cache/xml2rfc/reference.RFC.5912.xml for /Users/ur20980/.cache/xml2rfc/reference.RFC.5912.xml
** Can't manipulate reference XML: undefined method `attributes' for nil:NilClass
*** KRAMDOWN_OFFLINE: Inserting broken reference for reference.RFC.5912.xml
/Users/ur20980/.cache/xml2rfc/reference.RFC.5958.xml: fetching from https://www.rfc-editor.org/refs/bibxml/reference.RFC.5958.xml
*** execution expired while fetching https://www.rfc-editor.org/refs/bibxml/reference.RFC.5958.xml
/Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:1051:in `read': execution expired (Net::OpenTimeout)
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:1051:in `get_and_cache_resource'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:1137:in `block in convert_img'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:1123:in `scan'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:1123:in `convert_img'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:333:in `block in inner_a'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:331:in `map'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:331:in `inner_a'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:338:in `inner'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:351:in `convert_p'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:333:in `block in inner_a'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:331:in `map'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:331:in `inner_a'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:338:in `inner'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:1375:in `convert_root'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:326:in `convert1'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc2629.rb:321:in `convert'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-2.3.1/lib/kramdown/converter/base.rb:107:in `convert'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-2.3.1/lib/kramdown/document.rb:116:in `method_missing'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/lib/kramdown-rfc/command.rb:566:in `<top (required)>'
	from <internal:/opt/local/lib/ruby3.0/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/local/lib/ruby3.0/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/ur20980/.gem/ruby/3.0.0/gems/kramdown-rfc2629-1.6.5/bin/kramdown-rfc2629:3:in `<top (required)>'
	from /Users/ur20980/.local/bin/kramdown-rfc2629:25:in `load'
	from /Users/ur20980/.local/bin/kramdown-rfc2629:25:in `<main>'
Error: Unable to parse the XML document: /dev/stdin
make: *** [draft-turner-lamps-nist-pqc-kem-certificates.xml] Error 1
make: *** Deleting file `draft-turner-lamps-nist-pqc-kem-certificates.xml'
```

**Comment by seanturner** [comment]
> Maybe you can just point me at HTML or TXT (or PDF) version? TNX

If you go here and click on editor's version you will see the latest:
https://github.com/seanturner/draft-turner-lamps-nist-pqc-kem-certificates

**Comment by seanturner** [comment]
@mouse07410 is this still not compiling? I have updated to the latest workflow.

**Comment by seanturner** [comment]
@mouse07410 Just checking if you've checked ;)
